#! /bin/bash
root=/gpfs51/dors2/gpc/JamesBooth/JBooth-Lab/BDL/jinwang/mvpa_PhonReading_5_7
subjects_file_path=${root}
subjects_file=scripts/final_subj_info.txt #This should be a txt file with only a list of subject numbers
contrastsname=("onset_vs_perc_run1" "onset_vs_perc_run2" "rhyme_vs_perc_run1" "rhyme_vs_perc_run2" "unrelated_vs_perc_run1" "unrelated_vs_perc_run2");
contrasts=("con_0002.nii" "con_0003.nii" "con_0004.nii" "con_0005.nii" "con_0007.nii" "con_0008.nii"); #This should correspond to contrastsname
ROIs_path=('ses-5_postSTG_topvoxels_ROIs')
ROIs=('postSTG_allwords_vs_perc_p1_k500_adjust_mask')
data_path=preproc
firstlevelspm_path=analysis_ses-5/deweight

########do not need to modify below############
subjects=$(grep -Eo '[0-9\.]+' ${subjects_file_path}/${subjects_file})

#do roi loop
for roi_idx in ${!ROIs[@]}
do 

cd ${root}
mkdir extractedCon_${ROIs_path[roi_idx]}

#do contrast loop
for con_idx in ${!contrastsname[@]}
do 
cd ${root}/extractedCon_${ROIs_path[roi_idx]}
mkdir ${contrastsname[con_idx]}

#do subject loop
for sub in $subjects
do

cd ${root}/extractedCon_${ROIs_path[roi_idx]}_control/${contrastsname[con_idx]}
mkdir sub-${sub}
cd sub-${sub}
# find the coordinates and the t-values within a mask 
3dmaskdump \
-mask ${root}/${ROIs_path[roi_idx]}/sub-${sub}/${ROIs[roi_idx]}.nii \
${root}/${data_path}/sub-${sub}/${firstlevelspm_path}/${contrasts[con_idx]} > ${ROIs[roi_idx]}_${contrastsname[con_idx]}_output.txt

done  # end of subject loop

done  # end of contrast loop

done  # end of roi loop